"""Probe candidate company slugs against all three ATS APIs and emit verified YAML.

Job boards migrate constantly, so the company list is discovered empirically
rather than hand-asserted. Run this to (re)build config/companies.yml.
"""
from __future__ import annotations

import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from sources.base import http  # noqa: E402

PROBES = {
    "greenhouse": ("https://boards-api.greenhouse.io/v1/boards/{s}/jobs", lambda d: len(d.get("jobs", []))),
    "ashby": ("https://api.ashbyhq.com/posting-api/job-board/{s}", lambda d: len(d.get("jobs", []) or [])),
    "lever": ("https://api.lever.co/v0/postings/{s}?mode=json", lambda d: len(d) if isinstance(d, list) else -1),
}


def probe(slug: str, ats: str) -> int:
    url, counter = PROBES[ats]
    try:
        data = http(url.format(s=slug), expect_json=True, retries=2, timeout=25)
        return counter(data)
    except Exception:
        return -1


def probe_company(name: str, slug: str, tags: list[str]) -> dict | None:
    for ats in ("greenhouse", "ashby", "lever"):
        n = probe(slug, ats)
        if n > 0:
            return {"name": name, "ats": ats, "slug": slug, "tags": tags, "_n": n}
    return None


def main(candidates: list[tuple[str, str, list[str]]]) -> None:
    found, missing = [], []
    with ThreadPoolExecutor(max_workers=12) as pool:
        futs = {pool.submit(probe_company, n, s, t): (n, s) for n, s, t in candidates}
        for i, fut in enumerate(as_completed(futs), 1):
            name, slug = futs[fut]
            res = fut.result()
            if res:
                found.append(res)
                print(f"  [{i:3}/{len(candidates)}] OK   {res['ats']:10} {slug:28} {res['_n']:4} jobs", flush=True)
            else:
                missing.append(slug)
    print(f"\nVERIFIED {len(found)} / {len(candidates)}    (no public board: {len(missing)})")
    print("MISSING:", " ".join(sorted(missing)))
    out = Path(__file__).resolve().parent.parent / "data" / "verified_companies.yml"
    lines = ["# Auto-generated by scripts/probe_slugs.py -- verified live boards.", "companies:"]
    for c in sorted(found, key=lambda x: (x["tags"][0] if x["tags"] else "", x["name"].lower())):
        tags = ", ".join(c["tags"])
        lines.append(f'  - {{name: "{c["name"]}", ats: {c["ats"]}, slug: "{c["slug"]}", tags: [{tags}]}}  # {c["_n"]} jobs')
    out.write_text("\n".join(lines) + "\n")
    print("wrote", out)


if __name__ == "__main__":
    import json
    cands = json.loads(Path(sys.argv[1]).read_text())
    main([(c["name"], c["slug"], c["tags"]) for c in cands])
